Test for biceps 5-4-7_12_0
Draegerwerk/SDCcc pull request #11
Opened 2022-10-24 12:28 UTC by belagertem

Implemented a test for biceps 5-4-7_12_0. 
Added a manipulation to set the status of metrics with category 'clc' to  'calculation in progress'.

Added unit tests for biceps 5-4-7_12_0 and fixed comment in biceps 5-4-7_6_0 unit test.

2022-10-24 13:19 UTC, ldeichmann commented
> Added a manipulation to set the status of metrics with category 'clc' to 'calculation in progress'.

This is not really a new manipulation, but a new precondition.

2022-10-28 13:18 UTC, ldeichmann requested changes

2022-10-28 13:18 UTC, ldeichmann commented on sdccc/src/main/java/com/draeger/medical/sdccc/tests/biceps/invariant/InvariantParticipantModelStatePartTest.java
> +        testRequirement547(metricCategory, activationState);
no handling of `AbstractMetric`s transmitted through WaveformStream. This is not likely for Clc and Set, but for Msrmt it is not unlikely.

2022-11-03 11:54 UTC, ldeichmann requested changes

2022-11-03 15:23 UTC, belagertem commented on sdccc/src/main/java/com/draeger/medical/sdccc/tests/biceps/invariant/InvariantParticipantModelStatePartTest.java
> +            for (var part : ((AbstractMetricReport) report).getReportPart()) {
fixed

2022-11-04 09:41 UTC, ldeichmann approved these changes

2022-11-04 10:10 UTC, merged