Fixed NPE in Precondition
Draegerwerk/SDCcc pull request #135
Opened 2024-02-07 12:16 UTC by ben-Draeger

The DescriptionModificationUptPrecondition (amongst others) threw a NullPointerException when encountering a DescriptionModificationReport containing a ReportPart without a ModificationType attribute.

This should fix the problem.

# Checklist

The following aspects have been respected by the author of this pull request, confirmed by both pull request assignee **and** reviewer:

* Adherence to coding conventions
  * [ ] Pull Request Assignee
  * [ ] Reviewer
* Adherence to javadoc conventions
  * [ ] Pull Request Assignee
  * [ ] Reviewer
* Changelog update (necessity checked and entry added or not added respectively)
  * [ ] Pull Request Assignee
  * [ ] Reviewer
* README update (necessity checked and entry added or not added respectively)
  * [ ] Pull Request Assignee
  * [ ] Reviewer
* config update (necessity checked and entry added or not added respectively)
  * [ ] Pull Request Assignee
  * [ ] Reviewer
* SDCcc executable ran against a test device (if necessary)
  * [ ] Pull Request Assignee
  * [ ] Reviewer

2024-02-07 14:32 UTC, maximilianpilz requested changes
please fix the build, it failed, and change the copyright notice in the license headers of the files which you changed

2024-02-08 16:52 UTC, ben-Draeger commented
The licence header check fails because I updated the license header in the 2 files I touched.
This can be rectified by merging in the change from PR #134, which introduced a more powerful github action for licence header checking that can deal with this type of headers.

2024-02-12 14:57 UTC, maximilianpilz requested changes
please make use of the new license check from the main branch

2024-02-12 20:25 UTC, ben-Draeger commented
The Licence check was merged in from the main branch and it seems to work fine.

2024-02-15 08:51 UTC, maximilianpilz requested changes

2024-02-15 08:51 UTC, maximilianpilz commented on CHANGELOG.md
> +- potential NullPointerException in DescriptionModificationUptPrecondition.
```suggestion
- potential NullPointerException in DescriptionModificationUptPrecondition
```

2024-02-15 09:16 UTC, merged