Fixed Defect in Test Case for Glue:R0036_0.
Draegerwerk/SDCcc pull request #136
Opened 2024-02-09 16:52 UTC by ben-Draeger

Fixed Defect in Test Case for Glue:R0036_0.

# Checklist

The following aspects have been respected by the author of this pull request, confirmed by both pull request assignee **and** reviewer:

* Adherence to coding conventions
  * [x] Pull Request Assignee
  * [x] Reviewer
* Adherence to javadoc conventions
  * [x] Pull Request Assignee
  * [x] Reviewer
* Changelog update (necessity checked and entry added or not added respectively)
  * [x] Pull Request Assignee
  * [x] Reviewer
* README update (necessity checked and entry added or not added respectively)
  * [x] Pull Request Assignee
  * [x] Reviewer
* config update (necessity checked and entry added or not added respectively)
  * [x] Pull Request Assignee
  * [x] Reviewer
* SDCcc executable ran against a test device (if necessary)
  * [x] Pull Request Assignee
  * [x] Reviewer

2024-02-12 14:56 UTC, maximilianpilz requested changes
please make use of the new license check on the main branch and update the copyright notices in the files that you changed

2024-02-15 08:56 UTC, maximilianpilz requested changes

2024-02-15 08:56 UTC, maximilianpilz commented on CHANGELOG.md
> +- Test Case for Glue:R0036_0 now accepts SOAPFault as a valid answer for Subscribe messages.
```suggestion
- the test case for Glue:R0036_0 not accepting a SOAPFault as a valid answer for Subscribe messages
```

2024-02-15 08:58 UTC, maximilianpilz commented on sdccc/src/main/java/com/draeger/medical/sdccc/tests/glue/direct/DirectSubscriptionHandlingTest.java
> +                result = null;
add a log message here

2024-02-16 16:11 UTC, ben-Draeger commented on sdccc/src/main/java/com/draeger/medical/sdccc/tests/glue/direct/DirectSubscriptionHandlingTest.java
> +                result = null;
Done.

2024-02-19 11:57 UTC, maximilianpilz approved these changes

2024-02-19 11:58 UTC, merged