Support multi mds biceps r5042
Draegerwerk/SDCcc pull request #160
Opened 2024-04-18 11:25 UTC by jannast

Add support for multi mds for the requirements test biceps r5042 and update respective unit tests.

# Checklist

The following aspects have been respected by the author of this pull request, confirmed by both pull request assignee **and** reviewer:

* Adherence to coding conventions
  * [ ] Pull Request Assignee
  * [ ] Reviewer
* Adherence to javadoc conventions
  * [ ] Pull Request Assignee
  * [ ] Reviewer
* Changelog update (necessity checked and entry added or not added respectively)
  * [ ] Pull Request Assignee
  * [ ] Reviewer
* README update (necessity checked and entry added or not added respectively)
  * [ ] Pull Request Assignee
  * [ ] Reviewer
* config update (necessity checked and entry added or not added respectively)
  * [ ] Pull Request Assignee
  * [ ] Reviewer
* SDCcc executable ran against a test device (if necessary)
  * [ ] Pull Request Assignee
  * [ ] Reviewer

2024-04-25 14:12 UTC, belagertem requested changes

2024-04-26 05:39 UTC, jannast commented on sdccc/src/main/java/com/draeger/medical/sdccc/tests/biceps/direct/DirectParticipantModelServiceOperationsTest.java
>                          .map(mdibEntity -> (MdsDescriptor) mdibEntity.getDescriptor())
done

2024-04-26 05:39 UTC, jannast commented on sdccc/src/main/java/com/draeger/medical/sdccc/tests/biceps/direct/DirectParticipantModelServiceOperationsTest.java
> +            }
done

2024-04-26 05:45 UTC, jannast commented on sdccc/src/main/java/com/draeger/medical/sdccc/tests/biceps/direct/DirectParticipantModelServiceOperationsTest.java
> +        LOG.debug(
For me it is useful information, that´s why I add this as a debug information only. This documents the test case progress and can be useful for debugging.
But if it is not the sdccc way to do the reporting, I can remove this.

2024-04-26 05:58 UTC, jannast commented on sdccc/src/main/java/com/draeger/medical/sdccc/tests/biceps/direct/DirectParticipantModelServiceOperationsTest.java
> +        LOG.debug(
I improved the failing assertion message because the response as you wrote was not stated in the message. But now is.

2024-04-26 05:58 UTC, jannast commented on sdccc/src/main/java/com/draeger/medical/sdccc/tests/biceps/direct/DirectParticipantModelServiceOperationsTest.java
> +        LOG.debug(
doubled remark

2024-04-26 06:28 UTC, jannast commented on sdccc/src/test/java/com/draeger/medical/sdccc/tests/biceps/direct/DirectParticipantModelServiceOperationsTestTest.java
> +     * Assert that for multiple Mds the test results are correctly evaluated for each mds.
done

2024-04-26 07:10 UTC, jannast commented on sdccc/src/test/java/com/draeger/medical/sdccc/tests/biceps/direct/DirectParticipantModelServiceOperationsTestTest.java
> +    public void testRequirementR5042OneMdsPassed() throws NoTestData {
done

2024-04-26 07:10 UTC, jannast commented on sdccc/src/test/java/com/draeger/medical/sdccc/tests/biceps/direct/DirectParticipantModelServiceOperationsTestTest.java
> +        final var mdibEntity0 = createMdsContextStateEntity(mdsDescriptorHandle, "cH0");
done

2024-04-26 07:11 UTC, jannast commented on sdccc/src/test/java/com/draeger/medical/sdccc/tests/biceps/direct/DirectParticipantModelServiceOperationsTestTest.java
> +        final var mdibEntity0 = createMdsContextStateEntity(mdsDescriptorHandle, "cH0");
done

2024-04-26 07:11 UTC, jannast commented on sdccc/src/test/java/com/draeger/medical/sdccc/tests/biceps/direct/DirectParticipantModelServiceOperationsTestTest.java
> +        when(mdibEntity.getStates(any())).thenReturn(List.of(contextState));
done

2024-04-26 07:11 UTC, jannast commented on sdccc/src/test/java/com/draeger/medical/sdccc/tests/biceps/direct/DirectParticipantModelServiceOperationsTestTest.java
> +    private @NotNull MdibEntity createMdsContextStateEntity(final String mdsDescriptorHandle, final String handleName) {
it was automatically added during conversion. Removed this.

2024-04-26 08:46 UTC, belagertem requested changes

2024-04-26 08:46 UTC, belagertem commented on sdccc/src/test/java/com/draeger/medical/sdccc/tests/biceps/direct/DirectParticipantModelServiceOperationsTestTest.java
Currently, only a NoTestData unit test is implemented for the case that no mds are available. However, there should be a second unit test for the case that no ContextStates are available.
Please add a unit test for this case.

2024-04-26 08:46 UTC, belagertem commented on sdccc/src/test/java/com/draeger/medical/sdccc/tests/biceps/direct/DirectParticipantModelServiceOperationsTestTest.java
> +     * Assert that for multiple Mds the test results are correctly evaluated for each mds.
Actually NoTestData is thrown when no mds is present, or no context states are present.
I think in unit tests its also okay to just use _Exception_

So you could write something general like this:
"@throws Exception on any exception"

2024-04-26 08:57 UTC, jannast commented on sdccc/src/main/java/com/draeger/medical/sdccc/tests/biceps/direct/DirectParticipantModelServiceOperationsTest.java
>                          .map(mdibEntity -> (MdsDescriptor) mdibEntity.getDescriptor())
done

2024-04-26 08:59 UTC, jannast commented on sdccc/src/test/java/com/draeger/medical/sdccc/tests/biceps/direct/DirectParticipantModelServiceOperationsTestTest.java
> +     * Assert that for multiple Mds the test results are correctly evaluated for each mds.
done

2024-04-26 09:13 UTC, jannast commented on sdccc/src/test/java/com/draeger/medical/sdccc/tests/biceps/direct/DirectParticipantModelServiceOperationsTestTest.java
done

2024-04-26 11:45 UTC, belagertem approved these changes

2024-04-26 11:47 UTC, merged