Adapted test case for glue:R0036 to replacement requirement glue:R0036_0
Draegerwerk/SDCcc pull request #17
Opened 2022-10-25 14:39 UTC by ben-Draeger

Requirement Glue:R0036 has been replaced. Hence the test case needed to be adapted.

# Checklist

The following aspects have been respected by the author of this pull request, confirmed by both pull request assignee **and** reviewer:

* Adherence to coding conventions
  * [ ] Pull Request Assignee
  * [ ] Reviewer
* Adherence to javadoc conventions
  * [ ] Pull Request Assignee
  * [ ] Reviewer
* Changelog update (necessity checked and entry added or not added respectively)
  * [ ] Pull Request Assignee
  * [ ] Reviewer
* README update (necessity checked and entry added or not added respectively)
  * [ ] Pull Request Assignee
  * [ ] Reviewer
* SDCcc executable ran against a test device (if necessary)
  * [ ] Pull Request Assignee
  * [ ] Reviewer

2022-11-04 16:04 UTC, maximilianpilz requested changes
running DirectSubscriptionHandlingTest results in the following error:

> [Guice/MissingImplementation]: No implementation for CommunicationLog was bound.

2022-11-04 17:10 UTC, maximilianpilz requested changes
Now the unittest uses CommunicationLogDummyImpl and the TestSuite CommunicationLogImpl.

let both use CommunicationLogImpl

2022-11-07 14:23 UTC, ben-Draeger commented
> Now the unittest uses CommunicationLogDummyImpl and the TestSuite CommunicationLogImpl.
> 
> let both use CommunicationLogImpl

Done.

2022-11-08 14:31 UTC, maximilianpilz submitted a review, later dismissed

2022-11-08 14:37 UTC, maximilianpilz commented
README.md has to be updated, because there is one occurrence of R0036 there

2022-11-08 15:13 UTC, ben-Draeger commented
> README.md has to be updated, because there is one occurrence of R0036 there

Done.

2022-11-08 15:17 UTC, maximilianpilz approved these changes

2022-11-08 15:18 UTC, merged