Observing manipulations
Draegerwerk/SDCcc pull request #192
Opened 2024-07-30 14:02 UTC by ldeichmann

Adds a new kind of precondition which receives changes to the Mdib of the Device under Test and can react accordingly.

# Checklist

The following aspects have been respected by the author of this pull request, confirmed by both pull request assignee **and** reviewer:

* Adherence to coding conventions
  * [ ] Pull Request Assignee
  * [ ] Reviewer
* Adherence to javadoc conventions
  * [ ] Pull Request Assignee
  * [ ] Reviewer
* Changelog update (necessity checked and entry added or not added respectively)
  * [ ] Pull Request Assignee
  * [ ] Reviewer
* README update (necessity checked and entry added or not added respectively)
  * [ ] Pull Request Assignee
  * [ ] Reviewer
* config update (necessity checked and entry added or not added respectively)
  * [ ] Pull Request Assignee
  * [ ] Reviewer
* SDCcc executable ran against a test device (if necessary)
  * [ ] Pull Request Assignee
  * [ ] Reviewer

2024-07-30 14:03 UTC, ldeichmann commented on sdccc/src/main/java/com/draeger/medical/sdccc/tests/biceps/invariant/InvariantBicepsNormativeAnnexTest.java
> +    @RequirePrecondition(observingPreconditions = {DummyObservingPrecondition.Companion.class})
Remove

2024-07-30 14:03 UTC, ldeichmann commented on sdccc/src/main/java/com/draeger/medical/sdccc/manipulation/precondition/impl/DummyObservingPrecondition.kt
> +class DummyObservingPrecondition(injector: Injector) : BufferedObservingPrecondition(
Remove

2024-08-01 10:29 UTC, pstaeck requested changes

2024-08-02 08:50 UTC, belagertem requested changes

2024-08-02 08:50 UTC, belagertem commented on sdccc/src/main/java/com/draeger/medical/sdccc/tests/annotations/RequirePrecondition.kt
> +     * Manipulations to trigger.
Please adapt KDoc.

2024-08-02 08:50 UTC, belagertem commented on sdccc/src/main/java/com/draeger/medical/sdccc/manipulation/precondition/PreconditionRegistry.kt
> +     * Registers a manipulation precondition for running and observing before disconnecting from the DUT.
```suggestion
     * Registers an observing precondition for running and observing before disconnecting from the DUT.
```

2024-08-02 11:25 UTC, ldeichmann commented on sdccc/src/main/java/com/draeger/medical/sdccc/sdcri/testclient/TestClientMdibObserver.kt
> +        val states: Map<String, List<AbstractAlertState>>
I think all names are kinda dumb here, `statesMap` e.g. makes it sound like there is an alternative way to access states, but there isn't. I decided to keep the naming from the sdc-ri message we get them from

2024-08-02 11:55 UTC, pstaeck approved these changes

2024-08-05 05:14 UTC, jannast approved these changes

2024-08-06 06:04 UTC, belagertem approved these changes

2024-08-06 07:06 UTC, merged