Allow setting the Extension Version.
Draegerwerk/SDCcc pull request #207
Opened 2024-09-10 13:41 UTC by ben-Draeger

SDCcc Extensions need a way to log their Extension Version in addition to the SDCcc version.

# Checklist

The following aspects have been respected by the author of this pull request, confirmed by both pull request assignee **and** reviewer:

* Adherence to coding conventions
  * [ ] Pull Request Assignee
  * [ ] Reviewer
* Adherence to javadoc conventions
  * [ ] Pull Request Assignee
  * [ ] Reviewer
* Changelog update (necessity checked and entry added or not added respectively)
  * [ ] Pull Request Assignee
  * [ ] Reviewer
* README update (necessity checked and entry added or not added respectively)
  * [ ] Pull Request Assignee
  * [ ] Reviewer
* config update (necessity checked and entry added or not added respectively)
  * [ ] Pull Request Assignee
  * [ ] Reviewer
* SDCcc executable ran against a test device (if necessary)
  * [ ] Pull Request Assignee
  * [ ] Reviewer

2024-09-13 13:10 UTC, belagertem requested changes

2024-09-16 09:11 UTC, ben-Draeger commented on sdccc/src/main/java/com/draeger/medical/sdccc/TestSuite.java
> +                LOG.info("Starting SDCcc{}", versionString);
Done.

2024-09-16 09:11 UTC, ben-Draeger commented on sdccc/src/main/java/com/draeger/medical/sdccc/TestSuite.java
> +                LOG.info("Starting SDCcc{} with {} Extension", versionString, extensionVersion);
This Log-line does not exist anymore. Considered as resolved.

2024-09-16 13:42 UTC, belagertem requested changes

2024-09-16 13:42 UTC, belagertem commented on sdccc/src/main/java/com/draeger/medical/sdccc/TestSuite.java
> +     * @param logInitializationInfos Lambda that is called after the logger has been initialized and SDCcc's version
```suggestion
     * @param logInitializationInfos lambda that is called after the logger has been initialized and SDCcc's version
```

2024-09-18 07:03 UTC, merged