Reduce mdib historian nesting
Draegerwerk/SDCcc pull request #226
Opened 2024-12-11 16:00 UTC by midttuna

// Reduces the nesting in Test Cases by providing a consumer in MdibHistorian

# Checklist

The following aspects have been respected by the author of this pull request, confirmed by both pull request assignee **and** reviewer:

* Adherence to coding conventions
  * [ ] Pull Request Assignee
  * [ ] Reviewer
* Adherence to javadoc conventions
  * [ ] Pull Request Assignee
  * [ ] Reviewer
* Changelog update (necessity checked and entry added or not added respectively)
  * [ ] Pull Request Assignee
  * [ ] Reviewer
* README update (necessity checked and entry added or not added respectively)
  * [ ] Pull Request Assignee
  * [ ] Reviewer
* config update (necessity checked and entry added or not added respectively)
  * [ ] Pull Request Assignee
  * [ ] Reviewer
* SDCcc executable ran against a test device (if necessary)
  * [ ] Pull Request Assignee
  * [ ] Reviewer

2025-01-07 11:52 UTC, belagertem requested changes

2025-01-07 11:52 UTC, belagertem commented on sdccc/src/main/java/com/draeger/medical/sdccc/tests/util/MdibHistorian.java
You could also add a function for test cases that are checking the reports. E.g. biceps-C5, biceps-C11 - biceps-C15.

For example, I have used a predicate and a triconsumer here:
```
 public void processAllReports(
            final Predicate<AbstractReport> applicable
            final TriConsumer<RemoteMdibAccess, RemoteMdibAccess, AbstractReport> processor)
            throws IOException {
        try (final Stream<String> sequenceIds = this.getKnownSequenceIds()) {
            sequenceIds.forEach(sequenceId -> {
                RemoteMdibAccess first = null;
                RemoteMdibAccess second = null;
                try {
                    first = createNewStorage(sequenceId);
                    second = createNewStorage(sequenceId);
                } catch (PreprocessingException e) {
                    fail(e);
                }

                final var minimumMdibVersion = ImpliedValueUtil.getMdibVersion(first.getMdibVersion());
                try (final var reports = getAllUniqueReports(sequenceId, minimumMdibVersion)) {
                    for (final Iterator<AbstractReport> iterator = reports.iterator(); iterator.hasNext(); ) {
                        final AbstractReport report = iterator.next();
                        if (applicable.test(report)) {
                            second = applyReportOnStorage(second, report);
                            processor.accept(first, second, report);
                            first = applyReportOnStorage(first, report);
                        } else {
                            first = applyReportOnStorage(first, report);
                            second = applyReportOnStorage(second, report);
                        }
                    }
                } catch (PreprocessingException | ReportProcessingException e) {
                    fail(e);
                }
            });
        }
    }
```

2025-01-08 11:11 UTC, midttuna commented on sdccc/src/main/java/com/draeger/medical/sdccc/tests/util/MdibHistorian.java
> +    public void processSequenceIds(final Consumer<String> sequenceIdConsumer) throws IOException {
Removed

2025-01-08 11:12 UTC, midttuna commented on sdccc/src/main/java/com/draeger/medical/sdccc/tests/util/MdibHistorian.java
> +    public void processAllConsecutivePairs(final BiConsumer<RemoteMdibAccess, RemoteMdibAccess> processor)
Is now used in one place

2025-01-08 11:12 UTC, midttuna commented on sdccc/src/main/java/com/draeger/medical/sdccc/tests/util/MdibHistorian.java
> +     * Processes each RemoteMdibAccess for a given sequenceId using the provided processor.
Fixed

2025-01-08 11:12 UTC, midttuna commented on sdccc/src/main/java/com/draeger/medical/sdccc/tests/util/MdibHistorian.java
> +     * Processes each RemoteMdibAccess for a given sequenceId using the provided processor.
Fixed

2025-01-08 11:12 UTC, midttuna commented on sdccc/src/main/java/com/draeger/medical/sdccc/tests/util/MdibHistorian.java
Added and replaced for relevant TestCases

2025-01-09 07:46 UTC, belagertem approved these changes

2025-01-09 07:46 UTC, merged